apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: jaeger
spec:
  strategy: production
  ingress:
    enabled: false
  collector:
    options:
      collector.zipkin.host-port: ":9411"
    minReplicas: 2
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  query:
    minReplicas: 2
    maxReplicas: 5
  ui:
    options:
      dependencies:
        menuEnabled: true
