# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: jaeger
spec:
  strategy: production
  ingress:
    enabled: false
  collector:
    options:
      collector.zipkin.host-port: ":9411"
    minReplicas: 2
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
  query:
    replicas: 2
  ui:
    options:
      dependencies:
        menuEnabled: true
