apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jaeger
resources:
  - jaeger.yml
  - ingress.yml
  - sm.yml
  - job.yml

configMapGenerator:
  - name: jaeger-index-template
    files:
      - config/index-template.json
