apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger-query
spec:
  endpoints:
    - interval: 10s
      port: http-query
      scheme: http
      path: /metrics
  jobLabel: k8s-app
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger-query
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger-collector
spec:
  endpoints:
    - interval: 10s
      port: http-c-binary-trft
      scheme: http
      path: /metrics
  jobLabel: k8s-app
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger-collector
