apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger-collector
  name: collector-monitoring
spec:
  ports:
    - name: admin-http
      port: 14269
      protocol: TCP
      targetPort: 14269
  selector:
    app.kubernetes.io/name: jaeger-collector
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger-collector
spec:
  endpoints:
    - interval: 30s
      port: admin-http
  jobLabel: k8s-app
  selector:
    matchLabels:
      app: jaeger-collector
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger-query
  name: query-monitoring
spec:
  ports:
    - name: admin-http
      port: 16687
      protocol: TCP
      targetPort: 16687
  selector:
    app.kubernetes.io/name: jaeger-query
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger-query
spec:
  endpoints:
    - interval: 30s
      port: admin-http
  jobLabel: k8s-app
  selector:
    matchLabels:
      app: jaeger-query
