
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger-collector
spec:
  endpoints:
    - interval: 30s
      port: admin-http
  jobLabel: k8s-app
  selector:
    matchLabels:
      app: jaeger-collector
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger-query
spec:
  endpoints:
    - interval: 30s
      port: admin-http
  jobLabel: k8s-app
  selector:
    matchLabels:
      app: jaeger-query
