# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger-collector
  name: collector-monitoring
spec:
  ports:
    - name: admin-http
      port: 14269
      protocol: TCP
      targetPort: 14269
  selector:
    app.kubernetes.io/name: jaeger-collector
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger-query
  name: query-monitoring
spec:
  ports:
    - name: admin-http
      port: 16687
      protocol: TCP
      targetPort: 16687
  selector:
    app.kubernetes.io/name: jaeger-query
  type: ClusterIP