---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../operator
  - ../../istio
  - ../../kiali

patches:
  - target:
      kind: IstioOperator
      name: istio
    patch: |-
      - op: replace
        path: /spec/profile
        value: default
