apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong-mesh
  namespace: kong-mesh-system
spec:
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      app: kuma-control-plane