---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
commonLabels:
  app: kiali

resources:
  - ../../../katalog/istio-operator/kiali

configMapGenerator:
  - name: kiali
    behavior: replace
    files:
      - config/config.yaml

secretGenerator:
  - name: kiali
    behavior: replace
    envs:
      - secrets/kiali-auth.env
