# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
commonLabels:
  app: kiali

resources:
  - ../../../katalog/istio-operator/kiali

configMapGenerator:
  - name: kiali
    behavior: replace
    files:
      - config/config.yaml

secretGenerator:
  - name: kiali
    behavior: replace
    envs:
      - secrets/kiali-auth.env
