---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../full
  - ../../jaeger

patches:
  - target:
      kind: Jaeger
      name: jaeger
    patch: |-
      - op: add
        path: /spec/storage
        value:
          type: elasticsearch
          esIndexCleaner:
            enabled: true
            numberOfDays: 7
            schedule: "55 01 * * *"
          options:
            es:
              server-urls: http://elasticsearch.logging.svc:9200
              index-prefix: "jaeger"
              tags-as-fields:
                all: true
