apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kong-mesh-control-plane-kmesh
  labels:
    app.kubernetes.io/name: kong-mesh
    app.kubernetes.io/instance: kong-mesh
rules:
  - apiGroups:
      - kuma.io
    resources:
      - opapolicies
      - accessroles
      - accessrolebindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
