---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jaeger
resources:
  - crds/jaegertracing.io_jaegers_crd.yaml
  - cluster_role.yaml
  - cluster_role_binding.yaml
  - ns.yml
  - operator.yaml
  - service_account.yaml
  - sm.yml

patches:
  - target:
      kind: ClusterRoleBinding
      name: jaeger-operator
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: jaeger
  - target:
      kind: Deployment
      name: jaeger-operator
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0
        value:
            name: WATCH_NAMESPACE
            value: ""
