# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# From: https://github.com/jaegertracing/jaeger-operator/releases/download/v1.43.0/jaeger-operator.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: jaeger-operator
  name: jaeger-operator
  namespace: jaeger