---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger-operator
spec:
  endpoints:
    - interval: 10s
      port: http-metrics
      scheme: http
      path: /metrics
  jobLabel: k8s-app
  selector:
    matchLabels:
      name: jaeger-operator
