istio_component_namespaces:
  grafana: istio-system
  tracing: istio-system
  prometheus: monitoring
istio_namespace: istio-system
auth:
  strategy: "anonymous"
deployment:
  accessible_namespaces: ["**"]
  logger:
    log_level: trace
api:
  namespaces:
    exclude:
      - kube-public
      - kube-system
      - kube-node-lease
login_token:
  signing_key: "eto6tUSMft"
server:
  port: 20001
  web_root: /kiali
external_services:
  prometheus:
    url: http://prometheus-k8s.monitoring:9090
