# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma-control-plane
  namespace: kuma-system
spec:
  template:
    spec:
      containers:
        - name: control-plane
          env:
            - name: KUMA_MULTIZONE_GLOBAL_KDS_TLS_CERT_FILE
              value: "/var/run/secrets/kuma.io/kds-server-tls-cert/tls.crt"
            - name: KUMA_MULTIZONE_GLOBAL_KDS_TLS_KEY_FILE
              value: "/var/run/secrets/kuma.io/kds-server-tls-cert/tls.key"
          volumeMounts:
            - name: kds-server-tls-cert
              mountPath: /var/run/secrets/kuma.io/kds-server-tls-cert
              readOnly: true
      volumes:
        - name: kds-server-tls-cert
          secret:
            secretName: kds-server-tls