apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kuma
  namespace: kuma-system
spec:
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      app: kuma-control-plane