apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: istio-reader
    app.kubernetes.io/instance: istio
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-reader
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.25.2
    helm.sh/chart: base-1.25.2
    release: istio
  name: istio-reader-service-account
  namespace: istio-system
