# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  profile: minimal
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      defaultNodeSelector:
        {}
        # node.kubernetes.io/role: infra
      defaultTolerations:
        []
        # - key: " node-role.kubernetes.io/infra"
        #   operator: "Exists"
        #   effect: "NoSchedule"
  components:
    pilot:
      k8s:
        hpaSpec:
          maxReplicas: 10
          minReplicas: 2
    egressGateways:
    - name: istio-egressgateway
      enabled: false
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
        service:
      # the default is type LoadBalancer
      type: NodePort
      ports:
        - name: status-port
          port: 15021
          protocol: TCP
          targetPort: 15021
        - name: http2
          nodePort: 31380
          port: 80
          protocol: TCP
          targetPort: 8080
        - name: https
          nodePort: 31390
          port: 443
          protocol: TCP
          targetPort: 8443
        - name: tcp-istiod
          nodePort: 31400
          port: 15012
          protocol: TCP
          targetPort: 15012
        - name: tls
          port: 15443
          protocol: TCP
          targetPort: 15443