apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  components:
    pilot:
      k8s:
        hpaSpec:
          maxReplicas: 10
          minReplicas: 2
  # meshConfig:
  #   enableTracing: true
  #   defaultConfig:
  #     tracing:
  #       sampling: 100
  #       zipkin:
  #         address: jaeger-collector.jaeger.svc.cluster.local:9411
  profile: minimal
  values:
    global:
      defaultNodeSelector: {}
        # node.kubernetes.io/role: infra
      defaultTolerations: []
        # - key: " node-role.kubernetes.io/infra"
        #   operator: "Exists"
        #   effect: "NoSchedule"
    gateways:
      istio-ingressgateway:
        # the default is type LoadBalancer
        type: NodePort
        ports:
        - name: status-port
          port: 15021
          protocol: TCP
          targetPort: 15021
        - name: http2
          nodePort: 31380
          port: 80
          protocol: TCP
          targetPort: 8080
        - name: https
          nodePort: 31390
          port: 443
          protocol: TCP
          targetPort: 8443
        - name: tcp-istiod
          nodePort: 31400
          port: 15012
          protocol: TCP
          targetPort: 15012
        - name: tls
          port: 15443
          protocol: TCP
          targetPort: 15443
