apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  components:
    pilot:
      k8s:
        hpaSpec:
          maxReplicas: 10
          minReplicas: 2
  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100
        zipkin:
          address: jaeger-collector.jaeger.svc.cluster.local:9411
  profile: default
  values:
    global:
      defaultNodeSelector:
        {}
        # node.kubernetes.io/role: infra
      defaultTolerations:
        []
        # - key: " node-role.kubernetes.io/infra"
        #   operator: "Exists"
        #   effect: "NoSchedule"
    gateways:
      istio-ingressgateway:
        # the default is type LoadBalancer
        type: NodePort
