varReference:
  - path: data
    kind: ConfigMap
  - kind: Deployment
    path: spec/template/spec/nodeSelector
  - kind: Deployment
    path: spec/template/spec/tolerations[]/value
  - kind: IstioOperator
    path: spec/values/global/defaultNodeSelector
  - kind: IstioOperator
    path: spec/values/global/defaultTolerations[]/value
  - kind: Jaeger
    path: spec/tolerations[]/value
  - kind: Jaeger
    path: spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms[]/matchExpressions[]/values[]
