apiVersion: v1
kind: Service
metadata:
  name: kong-mesh-control-plane
  namespace: kong-mesh-system
  labels:
    app: kuma-control-plane
spec:
  ports:
    - port: 5680
      name: metrics
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-mesh-control-plane
  namespace: kong-mesh-system
spec:
  template:
    spec:
      containers:
        - name: control-plane
          ports:
            - containerPort: 5680