apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-mesh-control-plane
  namespace: kong-mesh-system
spec:
  template:
    spec:
      containers:
        - name: control-plane
          env:
            - name: KUMA_MULTIZONE_ZONE_KDS_ROOT_CA_FILE
              value: "/var/run/secrets/kuma.io/kds-client-tls-cert/ca.crt"
            - name: KMESH_MULTIZONE_ZONE_KDS_AUTH_CP_TOKEN_INLINE
              valueFrom:
                secretKeyRef:
                  name: cp-token
                  key: data
          volumeMounts:
            - name: kds-client-tls-cert
              mountPath: /var/run/secrets/kuma.io/kds-client-tls-cert
              readOnly: true
      volumes:
        - name: kds-client-tls-cert
          secret:
            secretName: kds-ca-certs