apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-mesh-control-plane
  namespace: kong-mesh-system
spec:
  template:
    spec:
      containers:
        - name: control-plane
          env:
            - name: KUMA_MULTIZONE_ZONE_NAME
              value: "<ZONE_NAME>"
            - name: KUMA_MULTIZONE_ZONE_GLOBAL_ADDRESS
              value: "grpcs://<GLOBAL_CP_ADDRESS>:<GLOBAL_CP_PORT>"