# Change the base path to point your vendor directory
bases:
  - ../vendor/katalog/service-mesh/istio/citadel
  - ../vendor/katalog/service-mesh/istio/sidecar-injection/configuration/base

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: cacerts
  files:
  - ca-cert.pem=certs/ca-cert.pem
  - ca-key.pem=certs/ca-key.pem
  - root-cert.pem=certs/root-cert.pem
  - cert-chain.pem=certs/cert-chain.pem

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: istio-citadel
  path: patches/istio-citadel.yaml

patchesStrategicMerge:
  # Be sure this is the correct istio-configuration configmap
  - patches/istio-sidecar-injector.yaml
