apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: docker.io/kumahq/kuma-cp
    newName: registry.sighup.io/fury/kumahq/kuma-cp
    newTag: 1.4.1
  - name: docker.io/kumahq/kuma-dp
    newName: registry.sighup.io/fury/kumahq/kuma-dp
    newTag: 1.4.1

patchesStrategicMerge:
  - patches/kuma-init-image.yaml

patchesJson6902:
  - path: patches/kuma-admission-webhook-cainjector.yaml
    target:
      group: admissionregistration.k8s.io
      version: v1
      kind: MutatingWebhookConfiguration
      name: kuma-admission-mutating-webhook-configuration
      namespace: kuma-system
  - path: patches/kuma-admission-webhook-cainjector.yaml
    target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingWebhookConfiguration
      name: kuma-validating-webhook-configuration
      namespace: kuma-system

resources:
  - resources/kuma-zone.yml
