---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-operator
resources:
  - crds/crd-operator.yaml
  - istio-operator-cr.yaml
  - istio-operator-crb.yaml
  - istio-operator-deployment.yaml
  - istio-operator-namespace.yaml
  - istio-operator-sa.yaml
  - istio-operator-svc.yaml

images:
  - name: gcr.io/istio-testing/operator
    newName: registry.sighup.io/fury/istio/operator
    newTag: 1.12.6
