# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-operator
resources:
  - crds/crd-operator.yaml
  - istio-operator-cr.yaml
  - istio-operator-crb.yaml
  - istio-operator-deployment.yaml
  - istio-operator-namespace.yaml
  - istio-operator-sa.yaml
  - istio-operator-svc.yaml

images:
  - name: gcr.io/istio-testing/operator
    newName: registry.sighup.io/fury/istio/operator
    newTag: 1.22.2
