---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-operator
resources:
  - https://raw.githubusercontent.com/istio/istio/1.9.4/manifests/charts/istio-operator/crds/crd-operator.yaml
  - https://raw.githubusercontent.com/istio/istio/1.9.4/manifests/charts/istio-operator/files/gen-operator.yaml
