# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

varReference:
  - path: data
    kind: ConfigMap
  - kind: Deployment
    path: spec/template/spec/nodeSelector
  - kind: Deployment
    path: spec/template/spec/tolerations[]/value
  - kind: IstioOperator
    path: spec/values/global/defaultNodeSelector
  - kind: IstioOperator
    path: spec/values/global/defaultTolerations[]/value
  - kind: Jaeger
    path: spec/tolerations[]/value
  - kind: Jaeger
    path: spec/affinity/nodeAffinity/requiredDuringSchedulingIgnoredDuringExecution/nodeSelectorTerms[]/matchExpressions[]/values[]
