apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
commonLabels:
  app: kiali
resources:
  - cluster-role.yml
  - deployment.yml
  - service.yml
  - sa.yml
  - viewer-cluster-role.yml
  - cluster-role-binding.yml
  - dashboards.yml
  - crd.yml

# images:
#   - name: quay.io/kiali/kiali
#     newName: gcr.io/vf-mc2dev-ca-lab/mirror/kiali/kiali
#     newTag: v1.27
#
configMapGenerator:
  - name: kiali
    files:
      - config/config.yaml

secretGenerator:
  - name: kiali
    envs:
      - secrets/kiali-auth.env
