apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
helmChartInflationGenerator:
  - chartRepoUrl: https://kiali.org/helm-charts
    chartName: kiali-server
    valuesLocal:
      items: #....
