# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
commonLabels:
  app: kiali
resources:
  - crd.yml
  - sa.yml
  - cluster-role.yml
  - cluster-role-binding.yml
  - deployment.yml
  - service.yml
  - dashboards.yml
  - sm.yml
  - controlplane-rb.yaml
  - controlplane-role.yaml
  - viewer-cr.yaml

configMapGenerator:
  - name: kiali
    files:
      - config/config.yaml

secretGenerator:
  - name: kiali
    envs:
      - secrets/kiali-auth.env
