apiVersion: v1
kind: Service
metadata:
  name: kiali
spec:
  type: ClusterIP
  ports:
    - name: http-kiali
      protocol: TCP
      port: 20001
    - name: http-metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: kiali
