apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: docker.io/kong/kuma-cp
    newName: registry.sighup.io/fury/kong/kuma-cp
    newTag: 2.4.3

patchesStrategicMerge:
  - patches/kuma-init-image.yaml

patchesJson6902:
  - path: patches/kuma-admission-webhook-cainjector.yaml
    target:
      group: admissionregistration.k8s.io
      version: v1
      kind: MutatingWebhookConfiguration
      name: kuma-admission-mutating-webhook-configuration
      namespace: kuma-system
  - path: patches/kuma-admission-webhook-cainjector.yaml
    target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingWebhookConfiguration
      name: kuma-validating-webhook-configuration
      namespace: kuma-system

resources:
  - resources/kuma-standalone.yml
