
# built by ./refresh.sh
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./customresourcedefinition-httproutes.gateway.networking.k8s.io.yaml
- ./customresourcedefinition-gatewayclasses.gateway.networking.k8s.io.yaml
- ./customresourcedefinition-referencegrants.gateway.networking.k8s.io.yaml
- ./customresourcedefinition-gateways.gateway.networking.k8s.io.yaml
- ./customresourcedefinition-grpcroutes.gateway.networking.k8s.io.yaml
