apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kong-mesh-control-plane
  namespace: kong-mesh-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kong-mesh-control-plane
subjects:
  - kind: ServiceAccount
    name: kong-mesh-control-plane
    namespace: kong-mesh-system
